(function(){var o,p;p={coffeescript_js:"https://raw.github.com/alecperkins/coffeetable/master/lib/coffee_script-1.1.1-min.js",style:{position:"fixed",top:"5px",right:"5px"},local_storage:true,ls_key:"coffee-table",multi_line:false};window.log=function(){return console.log(arguments)};window.dir=function(){return console.dir(arguments)};o=function(){function q(c){var d,b;if(c==null)c={};g=p;for(d in c){b=c[d];g[d]=b}k={widget:{position:""+g.style.position,top:""+g.style.top,right:""+g.style.right,
background:"rgba(255,255,255,0.9)",padding:"0",border:"2px solid white","z-index":"9999999","box-shadow":"0px 0px 4px #222","font-size":"12px","max-height":"95%","overflow-y":"scroll"},button:{"float":"right",background:"white",border:"1px solid #ccc",color:"#991111",cursor:"pointer"},button_active:{background:"#991111",color:"white"},textarea:{"font-family":"monospace","font-size":"15px","min-width":"400px",height:"22px",margin:"4px"},div:{display:"none"},ul:{margin:"8px",padding:"4px 4px 4px 16px",
"font-family":"monospace"},li:{padding:"4px 4px 4px 4px",cursor:"pointer"},span:{padding:"4px","text-align":"center",cursor:"pointer","float":"left",color:"#555","font-variant":"small-caps",display:"none"},a:{padding:"4px","text-align":"center",cursor:"pointer","float":"right",color:"#222","font-variant":"small-caps"},input:{"vertical-align":"middle"},p:{padding:"4px",margin:"0","float":"right",display:"inline-block",width:"80px",color:"#222","font-variant":"small-caps",display:"none","text-align":"right"}};
r={"function":{color:"#229922"},number:{color:"#222299"},string:{color:"#992222"},undefined:{color:"grey","font-style":"italic"},object:{},"boolean":{color:"#229999"}};s="            <div>                <button>CoffeeTable</button>                <span>clear</span>                <a href='https://github.com/alecperkins/coffeetable' target='_blank'>?</a>                <p>multiline <input type='checkbox'></p>                <div>                    <textarea></textarea>                    <ul></ul>                </div>            </div>        ";
v();w();g.local_storage&&x()}var a,m,y,t,h,j,v,x,n,w,r,g,k,s,z;r=k=a=g=null;s="";m=false;j=0;h={source:[],result:[]};x=function(){var c,d;d=typeof localStorage!=="undefined"&&localStorage!==null?localStorage.getItem("coffee-table"):void 0;if(d!=null){d=JSON.parse(d);c=function(){var b,e,i,f;if(typeof CoffeeScript!=="undefined"&&CoffeeScript!==null){f=[];e=0;for(i=d.length;e<i;e++){b=d[e];f.push(t(b))}return f}else return setTimeout(function(){return c()},500)};return c()}};t=function(c){var d,b,e,
i,f,l,u;j=-1;h.source.push(c);b=null;i=d=false;try{e=CoffeeScript.compile(c,{bare:true})}catch(A){d=true;b=A}if(b==null)try{l=eval(e)}catch(B){i=true;b=B}if(b!=null)l=b;h.result.push(l);u=h.source.length-1;f=$("<li>"+u+": <span>"+l+"</span></li>");f.css(k.li);f.find("span").css(r[typeof l]);if(d)f.css("color","orange");else i&&f.css("color","red");f.hover(function(){return f.css({background:"rgba(255,255,0,0.2)","list-style-type":"disc"})},function(){return f.css({background:"","list-style-type":""})});
f.click(function(){return n(false,u)});f.mousedown(function(){return f.css({background:"rgba(255,255,0,0.8)"})});f.mouseup(function(){return f.css({background:"rgba(255,255,0,0.2)"})});f.prependTo(a.ul);a.span.show();return typeof localStorage!=="undefined"&&localStorage!==null?localStorage.setItem(g.ls_key,JSON.stringify(h.source)):void 0};y=function(){a.ul.empty();h.source=[];h.result=[];typeof localStorage!=="undefined"&&localStorage!==null&&localStorage.removeItem(g.ls_key);return a.span.hide()};
n=function(c,d){if(c==null)c=false;if(d!=null)j=d+1;if(j===-1)j=h.source.length-1;else if(c)j+=1;else j-=1;if(h.source.length>1){a.textarea.val(h.source[j]);a.textarea.selectionStart=0;return a.textarea.selectionEnd=0}};z=function(){console.log("toggle multi");g.multi_line=!g.multi_line;return a.textarea.css("height",g.multi_line?"4em":k.textarea.height).focus()};w=function(){var c,d,b;b=$(s);a={widget:b,textarea:b.find("textarea"),ul:b.find("ul"),button:b.find("button"),div:b.find("div"),span:b.find("span"),
a:b.find("a"),input:b.find("input"),p:b.find("p")};for(d in a){c=a[d];c.css(k[d])}a.button.click(function(){if(m){a.button.css(k.button);a.div.hide();a.p.hide()}else{a.button.css(k.button_active);a.div.show();a.p.show();a.textarea.focus()}return m=!m});a.span.click(function(){return y()});a.span.hover(function(){return a.span.css("color","#991111")},function(){return a.span.css("color",k.span.color)});a.input.click(function(){return z()});a.textarea.bind("keydown",function(e){var i;i=a.textarea.val();
if(this.selectionStart===0)if(e.which===38){console.log(j);n()}else e.which===40&&n(true);if(e.which===13&&(!g.multi_line||e.shiftKey)){e.preventDefault();if(i!==""){t(i);return a.textarea.val("")}}else if(e.which===9){e.preventDefault();e=this.selectionStart;this.value=this.value.substring(0,e)+"    "+this.value.substring(e);this.selectionStart=e+4;return this.selectionEnd=e+4}});g.multi_line&&a.input.click();return b.appendTo("body")};v=function(){var c;if(window.CoffeeScript==null){c=document.createElement("script");
c.type="application/javascript";c.src=p.coffeescript_js;return $("head").append(c)}};q.prototype.show=function(){a.widget.show();return this};q.prototype.hide=function(){a.widget.hide();return this};return q}();window.CoffeeTable=o;$(document).ready(function(){return window.coffeetable_instance=new o(window.coffeetable_settings)})}).call(this);
