{exec} = require 'child_process'

task 'build', 'compile coffee, minify js, build annotated source', ->
  exec 'coffee -o ../ -c coffeetable.coffee', (err, stdout, stderr) ->
    throw err if err
    console.log stdout
    console.log stderr
    exec 'closure --js_output_file ../coffeetable-min.js --js ../coffeetable.js', (err, stdout, stderr) ->
      throw err if err
      console.log stdout
      console.log stderr
  # exec 'python ~/forks/pycco/pycco/main.py coffeetable.coffee', (err, stdout, stderr) ->
  #   throw err if err
  #   console.log stdout
  #   console.log stderr